/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tpfinal.fabricaswing.vistas;

import com.tpfinal.fabricaswing.entidades.MateriaPrima;
import com.tpfinal.fabricaswing.entidades.Producto;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author Lautaro
 */
public class StockView extends javax.swing.JPanel {

    private List<MateriaPrima> materiasPrimas;
    private List<Producto> productos;
    private DefaultListModel<String> modelNombres;
    private DefaultListModel<String> modelExistencias;
    private DefaultListModel<String> modelRanking;
    private final String datosStock = "materias_primas.txt";
    private final String datosProductos = "productos.txt";

    /**
     * Creates new form StockView
     */
    public StockView() {
        this.setSize(300, 700);
        materiasPrimas = new ArrayList<>();
        productos = new ArrayList<>();
        modelNombres = new DefaultListModel<>();
        modelExistencias = new DefaultListModel<>();
        modelRanking = new DefaultListModel<>();
        initComponents();

        cargarDatosDesdeArchivo(new File(datosStock));
        cargarProductosDesdeArchivo(new File(datosProductos));
        actualizarListas();
        contarUsoMateriasPrimas();

        // Añadir ListSelectionListener a jList1
        jList1.addListSelectionListener((ListSelectionEvent e) -> {
            if (!e.getValueIsAdjusting()) {
                String materiaPrimaSeleccionada = jList1.getSelectedValue();
                if (materiaPrimaSeleccionada != null) {
                    actualizarRanking(materiaPrimaSeleccionada);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ranking = new javax.swing.JList<>();

        setPreferredSize(new java.awt.Dimension(300, 700));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Listado Materias Primas");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Agregar Materia Prima");

        jLabel3.setText("Nombre");

        jLabel4.setText("Cantidad");

        jButton1.setText("Agregar");
        jButton1.setPreferredSize(new java.awt.Dimension(150, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Materia Prima mas Utilizada");

        ranking.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(ranking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarRanking(String materiaPrimaSeleccionada) {
        Map<String, Integer> usoMateriasPrimas = new HashMap<>();

        for (Producto producto : productos) {
            int cantidad = contarMateriaPrimaEnProducto(producto, materiaPrimaSeleccionada);
            if (cantidad > 0) {
                usoMateriasPrimas.put(producto.getNombre(), cantidad);
            }
        }

        modelRanking.clear();
        usoMateriasPrimas.entrySet().stream()
                .sorted((entry1, entry2) -> entry2.getValue().compareTo(entry1.getValue()))
                .forEach(entry -> modelRanking.addElement(entry.getKey() + " - " + entry.getValue()));

        ranking.setModel(modelRanking);
    }

    private int contarMateriaPrimaEnProducto(Producto producto, String materiaPrimaSeleccionada) {
        int count = 0;

        for (Object materia : producto.getMateriasPrimas()) {
            if (materia instanceof MateriaPrima) {
                if (((MateriaPrima) materia).getNombre().equalsIgnoreCase(materiaPrimaSeleccionada)) {
                    count++;
                }
            } else if (materia instanceof Producto) {
                // Buscar el producto correspondiente en la lista de productos
                Producto subProducto = null;
                for (Producto p : productos) {
                    if (p.getNombre().equalsIgnoreCase(((Producto) materia).getNombre())) {
                        subProducto = p;
                        break;
                    }
                }

                if (subProducto != null) {
                    // Recursivamente contar las materias primas en el producto compuesto
                    count += contarMateriaPrimaEnProducto(subProducto, materiaPrimaSeleccionada);
                }
            }
        }
        return count;
    }

    private void cargarDatosDesdeArchivo(File file) {
        if (!file.exists()) {
            try {
                file.createNewFile();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al crear el archivo: " + e.getMessage());
            }
        }

        try (BufferedReader br = new BufferedReader(new FileReader(datosStock))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length == 2) {
                    String nombre = partes[0].trim();
                    int existencia = Integer.parseInt(partes[1].trim());
                    MateriaPrima materia = new MateriaPrima(nombre, existencia);
                    materiasPrimas.add(materia);
                }
            }
        } catch (IOException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos desde el archivo: " + e.getMessage());
        }
    }

    private void cargarProductosDesdeArchivo(File file) {
        if (!file.exists()) {
            try {
                file.createNewFile();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al crear el archivo: " + e.getMessage());
            }
        }

        try (BufferedReader br = new BufferedReader(new FileReader(datosProductos))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                if (partes.length >= 2) {
                    String nombre = partes[0].trim();
                    List<Object> materiasPrimasProducto = new ArrayList<>();
                    for (int i = 1; i < partes.length; i++) {
                        String materia = partes[i].trim();
                        Producto productoExistente = buscarProductoPorNombre(materia);
                        if (productoExistente != null) {
                            materiasPrimasProducto.add(productoExistente);
                        } else {
                            MateriaPrima materiaPrimaExistente = buscarMateriaPrimaPorNombre(materia);
                            if (materiaPrimaExistente != null) {
                                materiasPrimasProducto.add(materiaPrimaExistente);
                            } else {
                                // Si no es una materia prima existente, puede ser un producto nuevo
                                // Creamos un producto temporal y lo agregamos a la lista
                                Producto nuevoProducto = new Producto(materia, new ArrayList<>());
                                System.out.println("Cargando producto" + materia);
                                materiasPrimasProducto.add(nuevoProducto);
                            }
                        }
                    }
                    Producto producto = new Producto(nombre, materiasPrimasProducto);
                    productos.add(producto);
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar productos desde el archivo: " + e.getMessage());
        }
    }

    private void guardarDatosEnArchivo() {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(datosStock))) {
            for (MateriaPrima materia : materiasPrimas) {
                bw.write(materia.getNombre() + "," + materia.getExistencia());
                bw.newLine();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar datos en el archivo: " + e.getMessage());
        }
    }

    private Producto buscarProductoPorNombre(String nombre) {
        for (Producto producto : productos) {
            if (producto.getNombre().equalsIgnoreCase(nombre)) {
                return producto;
            }
        }
        return null;
    }

    private MateriaPrima buscarMateriaPrimaPorNombre(String nombre) {
        for (MateriaPrima materiaPrima : materiasPrimas) {
            if (materiaPrima.getNombre().equalsIgnoreCase(nombre)) {
                return materiaPrima;
            }
        }
        return null;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = jTextField1.getText().trim();
        String existenciaStr = jTextField2.getText().trim();

        if (nombre.isEmpty() || existenciaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete ambos campos.");
            return;
        }

        int existencia;
        try {
            existencia = Integer.parseInt(existenciaStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Existencia debe ser un número entero.");
            return;
        }

        for (MateriaPrima materia : materiasPrimas) {
            if (materia.getNombre().equalsIgnoreCase(nombre)) {
                materia.setExistencia(materia.getExistencia() + existencia);
                actualizarListas();
                guardarDatosEnArchivo();
                return;
            }
        }

        MateriaPrima nuevaMateria = new MateriaPrima(nombre, existencia);
        materiasPrimas.add(nuevaMateria);
        actualizarListas();
        guardarDatosEnArchivo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void actualizarListas() {
        modelNombres.clear();
        modelExistencias.clear();

        for (MateriaPrima materia : materiasPrimas) {
            modelNombres.addElement(materia.getNombre());
            modelExistencias.addElement(String.valueOf(materia.getExistencia()));
        }

        jList1.setModel(modelNombres);
        jList2.setModel(modelExistencias);
    }

    private void contarUsoMateriasPrimas() {
        Map<String, Integer> contadorMateriasPrimas = new HashMap<>();

        for (Producto producto : productos) {
            contarMateriasPrimasProducto(producto, contadorMateriasPrimas);
        }

        modelRanking.clear();
        contadorMateriasPrimas.entrySet().stream()
                .sorted((entry1, entry2) -> entry2.getValue().compareTo(entry1.getValue()))
                .forEach(entry -> modelRanking.addElement(entry.getKey() + ": " + entry.getValue()));

        ranking.setModel(modelRanking);
    }

    private void contarMateriasPrimasProducto(Producto producto, Map<String, Integer> contador) {
        for (Object materia : producto.getMateriasPrimas()) {
            if (materia instanceof Producto) {
                contarMateriasPrimasProducto((Producto) materia, contador);
            } else if (materia instanceof MateriaPrima) {
                String nombreMateria = ((MateriaPrima) materia).getNombre();
                contador.put(nombreMateria, contador.getOrDefault(nombreMateria, 0) + 1);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JList<String> ranking;
    // End of variables declaration//GEN-END:variables
}
